In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

[
  [  # 第1层
    [0, 0, 0, 0],  # 第1行
    [0, 0, 0, 0],  # 第2行  
    [0, 0, 0, 0]   # 第3行
  ],
  [  # 第2层
    [0, 0, 0, 0],  # 第1行
    [0, 0, 0, 0],  # 第2行
    [0, 0, 0, 0]   # 第3行
  ]
]

In [7]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]).shape

torch.Size([1, 3, 4])

In [14]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y, x-y, x*y, x/y, x**y #**是求平方

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [15]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [18]:
x = torch.arange(12,dtype = torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
# cat合并 dim=0按行合并-叠起来，dim=1按列合并，拼起来
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [19]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [20]:
x.sum()

tensor(66.)

In [22]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

广播机制 > 会补一样的元素，eg单列那个会补一列和自己本身一样的列
即使形状不同，我们仍然可以通过调用广播机制(broadcasting mechanism)来执行元素操作

In [23]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [24]:
# 可以用[-1]选择最后一个元素
# 可以用[1:3]选择第二个和第三个元素
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [25]:
#可以把元素写入矩阵
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
#为多个元素赋值
x[0:2,:] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [27]:
#运行一些操作可能会导致为新结果分配内存
before = id(y)
y = y + x
id(y) == before

False

In [29]:
#执行原地操作
z = torch.zeros_like(y)
print('id(z):',id(z))
z[:] = x + y
print('id(z):',id(z))

id(z): 1881819444912
id(z): 1881819444912


In [30]:
#如果在后续计算中没有重复使用x，我们也可以使用x[:] = x + y 或 x += y 来减少操作的内存开销
before = id(x)
x += y
id(x) ==before

True

In [31]:
#转换为NumPy张量
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [32]:
#将大小为1的张量转换为Python标量
a = torch.tensor([3.5])
a, a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)